//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int Id { get; set; }
        public Nullable<int> acctNo { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<int> balance { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    }
}
